# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            hiijack
#tagline:          'Blog'
description:      'Blog'
url:              https://github.com/hiijack/
baseurl:          /

author:
  name:           'hiijack'
  url:            https://github.com/hiijack/

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/hiijack/
